#!/usr/bin/env bash
# Builds a signed, installable release APK for Medical Navigator.
#
#   ./tools/build.sh
#
# Stages: aapt2 compile -> aapt2 link -> javac -> dx -> align -> sign -> verify.
# Output: dist/MedicalNavigator-<version>.apk
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TOOLCHAIN="${TOOLCHAIN:-$ROOT/.toolchain}"
BUILD="$ROOT/build"
SRC="$ROOT/app/src/main"
DIST="$ROOT/dist"
KEYSTORE="${KEYSTORE:-$ROOT/.keystore/mednav.p12}"
KEY_ALIAS="${KEY_ALIAS:-mednav}"
KEY_PASS="${KEY_PASS:-mednav-pilot}"

MIN_SDK=24
TARGET_SDK=34
VERSION_NAME="$(sed -n 's/.*android:versionName="\([^"]*\)".*/\1/p' "$SRC/AndroidManifest.xml" | head -1)"
VERSION_CODE="$(sed -n 's/.*android:versionCode="\([^"]*\)".*/\1/p' "$SRC/AndroidManifest.xml" | head -1)"
APK_NAME="MedicalNavigator-v$VERSION_NAME.apk"

# apksig 2.3.0 reaches into sun.security.*, which is not exported by default on
# JDK 9+. Opening those two packages is enough; nothing else needs it.
JVM_OPEN=(--add-exports java.base/sun.security.x509=ALL-UNNAMED
          --add-exports java.base/sun.security.pkcs=ALL-UNNAMED)

step() { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }

[ -x "$TOOLCHAIN/aapt2" ] || { step "Toolchain missing, fetching"; "$ROOT/tools/fetch-toolchain.sh"; }

step "Clean"
rm -rf "$BUILD"
mkdir -p "$BUILD"/{flat,gen,classes,apk} "$DIST"

step "Generate BuildInfo"
mkdir -p "$BUILD/gen/com/mednav/navigator"
cat > "$BUILD/gen/com/mednav/navigator/BuildInfo.java" <<JAVA
package com.mednav.navigator;

/** Generated by tools/build.sh - do not edit. */
final class BuildInfo {
    private BuildInfo() { }
    static final String VERSION_NAME = "$VERSION_NAME";
    static final int VERSION_CODE = $VERSION_CODE;
    static final String BUILD_STAMP = "$(date -u '+%Y-%m-%d %H:%M UTC')";
}
JAVA

step "Compile resources (aapt2 compile)"
"$TOOLCHAIN/aapt2" compile --dir "$SRC/res" -o "$BUILD/flat/res.zip"

step "Link resources + assets (aapt2 link)"
"$TOOLCHAIN/aapt2" link \
  -o "$BUILD/apk/base.apk" \
  --manifest "$SRC/AndroidManifest.xml" \
  -I "$TOOLCHAIN/android-framework.jar" \
  -A "$SRC/assets" \
  --java "$BUILD/gen" \
  --min-sdk-version "$MIN_SDK" \
  --target-sdk-version "$TARGET_SDK" \
  --no-version-vectors \
  "$BUILD/flat/res.zip"

step "Compile Java (javac -> $MIN_SDK-compatible bytecode)"
# -source/-target 8 rather than --release 8: the Android framework classes come
# from a jar on the classpath, so the JDK's own platform API must stay visible
# to javac while the emitted bytecode stays at class file version 52 for dx.
find "$SRC/java" "$BUILD/gen" -name '*.java' > "$BUILD/sources.txt"
javac -source 8 -target 8 -encoding UTF-8 -nowarn \
  -Xlint:-options \
  -classpath "$TOOLCHAIN/android.jar" \
  -d "$BUILD/classes" \
  @"$BUILD/sources.txt" 2>&1 | grep -v '^Picked up' || true
[ -f "$BUILD/classes/com/mednav/navigator/MainActivity.class" ] \
  || { echo "javac produced no MainActivity.class"; exit 1; }

step "Dex (dx)"
java -cp "$TOOLCHAIN/dalvik-dx.jar" com.android.dx.command.Main \
  --dex --min-sdk-version="$MIN_SDK" \
  --output="$BUILD/classes.dex" "$BUILD/classes" 2>&1 | grep -v '^Picked up' || true
[ -s "$BUILD/classes.dex" ] || { echo "dx produced no classes.dex"; exit 1; }

step "Package + align"
python3 "$ROOT/tools/zipalign.py" \
  "$BUILD/apk/base.apk" "$BUILD/classes.dex" "$BUILD/apk/aligned.apk"

step "Sign (APK Signature Scheme v2)"
if [ ! -s "$KEYSTORE" ]; then
  echo "  creating a new signing key at $KEYSTORE"
  echo "  KEEP THIS FILE: a different key means users must uninstall before upgrading."
  mkdir -p "$(dirname "$KEYSTORE")"
  keytool -genkeypair -keystore "$KEYSTORE" -storetype PKCS12 \
    -storepass "$KEY_PASS" -keypass "$KEY_PASS" -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 2048 -validity 10950 \
    -dname "CN=Medical Navigator Pilot, OU=MVP, O=Medical Navigator, C=IN" \
    2>&1 | grep -v '^Picked up' || true
fi
mkdir -p "$BUILD/signer"
javac -classpath "$TOOLCHAIN/apksig.jar" -d "$BUILD/signer" \
  "$ROOT/tools/signer/ApkTool.java" 2>&1 | grep -v '^Picked up' || true
java "${JVM_OPEN[@]}" -cp "$TOOLCHAIN/apksig.jar:$BUILD/signer" ApkTool sign \
  "$KEYSTORE" "$KEY_PASS" "$KEY_ALIAS" "$KEY_PASS" \
  "$BUILD/apk/aligned.apk" "$DIST/$APK_NAME" "$MIN_SDK" 2>&1 | grep -v '^Picked up'

step "Verify"
java "${JVM_OPEN[@]}" -cp "$TOOLCHAIN/apksig.jar:$BUILD/signer" ApkTool verify \
  "$DIST/$APK_NAME" "$MIN_SDK" 2>&1 | grep -v '^Picked up'
"$TOOLCHAIN/aapt2" dump badging "$DIST/$APK_NAME" | head -8

printf '\n\033[1;32mBuilt %s (%s)\033[0m\n' \
  "$DIST/$APK_NAME" "$(du -h "$DIST/$APK_NAME" | cut -f1)"
